- code/obj/flock/structure/sentinel.dm
Fixes #9 - a mistake in sentinel code that caused a runtime
Tweaks efficiency of targetting code
Prevents sentinels from targetting dead/intangible things
> Fixes #9 - Sentinel no longer runtimes, also efficiency fix, also no targetting ghosts fix

- code/mob/living/critter/flock/flockdrone.dm
[BUG]
Fixes #21 
Deleting resources is sad
> Drones now drop their resources when diffracted

- code/mob/living/critter/flock/flockdrone.dm
[FEATURE] [QOL]
Fixes #18
Might be nice to have a way to turn it off for sneaking, but flockdrones really need a way to see in the dark.
> Flockdrones now glow

- code/datums/abilities/flock/flockmind.dm
[BUG]
This PR prevents cancelling the Fabricate Structure ability from applying its cooldown.
Bug fix, fixes #38.
> Prevent cancelling Fabricate Structure ability from applying the ability cooldown

- code/datums/abilities/flock/flockmind.dm
[BUG]
This PR prevents you from using the Concentrated Repair Burst ability on drones that have full health.
Bug fix, fixes #41.
> Fix using Concentrated Repair Burst ability on drones with full health

- code/mob/living/intangible/flock/flockmind.dm
- code/mob/living/intangible/flock/flocktrace.dm
This PR just gives the Flockmind and Flocktraces their own layers, the same as what blob has.
They did not appear to have explicitly defined layers.
> Give Flockmind and Flocktrace layers

- code/datums/abilities/flock/flockmind.dm
[BUG]
This PR prevents designating things that shouldn't be designated as an enemy with the Designate Enemy ability.
Bug fix, fixes #43.
> Fix designating as enemy things that shouldn't be designated using the Designate Enemy ability.

- code/obj/flock/structure/rift.dm
[FEATURE]
This PR just anchors the Flockmind rift.
It wouldn't be good if it could be moved.
> Anchor Flockmind rift

- code/datums/flock/flock.dm
[BUG]
This PR makes it so that catwalks are converted only to a Flock floor tile. Previously they were converted to a Flock barricade on either a Flock floor tile or a fibrenet.
Bug fix.
> Fix catwalk conversion

- code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR just fixes a bug where shooting a Flockdrone would not designate you as an enemy.
Bug fix
> Fix shooting Flockdrones not designating you as an enemy

- code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR fixes a bug where grabs could be put in the disintegration reclaimer.
Bug fix, fixes #69.
> Fix putting grabs in the disintegration reclaimer

- code/obj/flock/structure/flock_structure_ghost.dm
- code/procs/mobprocs/chatprocs.dm
[FEATURE]
This PR allows structures to give a SYSTEM message on the Flock channel with the word SYSTEM being a link that you can click on to teleport to the structure as Flockmind.
It would look like this but with SYSTEM a link.
It would be useful for viewing the structure when it gives a message.
> Allow structures to give a SYSTEM message on the Flock channel

- code/mob/living/intangible/flock/flockmind.dm
> Prevents flockminds from teleporting to deleted drones

- code/datums/flock/flock.dm
This PR just changes the alert for destroying a Flocktrace to a tgui prompt.
tgui looks a little nicer.
> Use tgui prompt for destroying a Flocktrace

- code/mob/living/critter/ai/flock/flocktasks.dm
Fixes #1 
It seems the author really wanted to handle picking up items like a player does. I fixed that a bit, and made it so locked or awkward containers get eaten even if they can't open them normally.
> Fixes a couple issues with items being awkward

- code/obj/flock/structure/relay.dm
- code/obj/item/device/radio.dm
- code/procs/mobprocs/chatprocs.dm
[FEATURE]
Upon final relay activation, all headsets on the map are irreparably bricked.
Silence, but for the echoes of the Signal.
The lack of comms adds to the feeling that everything is fucked and you should probably just leave.
> Flock victory destroys all radios

- code/mob/living/critter/flock/flockdrone.dm
> fixes runtime on difract in space

- code/mob/living/critter/ai/flock/flocktasks.dm
[BUG]
Fixes #173 
The dinging was getting to me.
> Flockdrones can now eat bells

- code/mob/living/critter/flock/flockbit.dm
- code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR just fixes Flockdrone system integrity being shown to be less than 0% on examine.
Added it for Flockbits too, they are supposed to die at 0% health so not sure if this is needed.
Bug fix.
> Fix Flockdrone system integrity showing to be less than 0%

- code/datums/abilities/flock/flockmind.dm
[FEATURE]
This PR just establishes some ability cooldowns for the Flockmind abilities, using temporary but hopefully reasonable numbers, based off the tradeoffs/functionality/power of the abilities.
The abilities were using default cooldowns and didn't have established cooldowns.
> Add ability cooldowns

- code/mob/living/critter/flock/flockbit.dm
- code/mob/living/critter/flock/flockdrone.dm
- code/obj/flock/furniture.dm
- code/obj/flock/structure/flock_structure_parent.dm
- code/obj/machinery/door/feather.dm
[FEATURE]
This PR makes it so that Flock stuff can't be damaged by the incapacitor.
Incapacitor shouldn't be able to harm Flock stuff.
Fixes #176.
> Prevent damaging Flock stuff with incapacitor

- code/datums/flock/flock.dm
- code/datums/flock/flockunlockable.dm
- code/modules/admin/admin_verbs.dm
[QOL]
Adds a debug admin verb to toggle cheatmode on a flock, also makes cheatmode give you a million total compute.
Makes debug easier, can always revert it later to avoid spamming the debug pane.
> Adds flock cheatmode admin verb

- _std/macros/atom_properties.dm
- code/datums/flock/flock.dm
[feature]
atom properties
Closes #196
> atom property on things

- code/mob/living/critter/flockcritter_parent.dm
This PR just changes the color of Flock depositing after the first deposit to the color when first depositing.
Keeping color same looks a little nicer.
> Change color for Flock depositing after first deposit

- code/obj/mining.dm
[BUG]
This PR fixes being able to use the cargo teleporter on Flock closets.
Bug fix.
> Fix being able to use cargo teleporters on Flock closets

- code/modules/admin/admin.dm
Flock(probably wont work. Press at own risk) -> Flock(Beta)
> very important

- code/mob/living/critter/flock/flockbit.dm
- code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR adds proper disposing for Flockdrones and Flockbits.
They didn't have proper disposing, and it fixes bugs that arise because of it.
Fixes #220.
> Add proper disposing for Flockdrones and Flockbits

- code/datums/flock/flock.dm
- code/mob/living/critter/flock/flockbit.dm
- code/mob/living/critter/flock/flockdrone.dm
- code/mob/living/critter/flockcritter_parent.dm
- code/obj/flock/structure/flock_structure_ghost.dm
- code/obj/flock/structure/flock_structure_parent.dm
Makes flock beeps quieter, so you can be sneakier when you deploy.
Play test revealed that the flock could be heard from half the station away. this is bad.
> shut up you stupid birds

- code/mob/living/critter/ai/shared.dm
Fixes #234 by increasing move pathing limit.
> Fix rallying over long distances

- code/mob/living/critter.dm
- code/mob/living/critter/flock/flockdrone.dm
Should prevent all cases of this I think.
Fixes #251
> Stop animation when stuff is taken out of the absorber

- code/mob/living/critter/flock/flockdrone.dm
> quick fix to not move bits onto dense tiles

- code/datums/critter_mobs/equipment.dm
- code/mob/living/critter/ai/flock/flocktasks.dm
- code/mob/living/critter/flock/flockdrone.dm
- code/modules/materials/Mat_ProcsDefines.dm
Fixes #269 
Fixes #271 
Fixes #272
the #269 fix is a little hacky, but kinda makes sense. Basically I just made it so it wouldn't do rummaging if it was already eating, since it seemed to trigger the uninterruptible animation only when trying to eat a container when you're already eating another container. I don't know why.
> More anim fixes

- code/mob/living/critter/ai/flock/flocktasks.dm
- code/mob/living/critter/ai/shared.dm
- code/obj/flock/cage.dm
- code/obj/flock/structure/flock_structure_ghost.dm
- code/procs/helpers.dm
Gonna do some minor tweaks to flock AI to make it more efficient.
> Efficient AI please

- code/datums/flock/flock.dm
[BUG]
Some QDELETED checks that were missing and causing runtimes
Fixes what seems to have been determined as the actual issue from #140
runtimes bad
> Fixes deleted enemies causing runtimes

- code/datums/flock/flock.dm
- code/modules/sound/soundCache.dm
[CLEANLINESS]
Adds the flock ping sound effect to the sound cache
i forgor
> Added ping sound file to sound cache

- code/mob/living/critter/flock/flockdrone.dm
There was only one instance of this.
Fixes #308
> you need FLOCK

- code/mob/living/critter/ai/flock/flocktasks.dm
Adds a check to make sure the item is on the ground before we try to eat it, in case someone already picked it up.
> fix race condition with paper bins

- code/datums/abilities/flock/flockmind.dm
[CLEANLINESS]
Some weird ability delays plus Aloe's dota 2 flashbacks.
> Adjusted some ability timings

- code/datums/abilities/flock/flockmind.dm
[BUG]
Adds some messages on trying to cast abilities on dead drones.
> Feedback on casting abilities on dead drones

- _std/pathfinding.dm
- code/obj/machinery/door/door_parent.dm
- code/obj/machinery/door/feather.dm
[CLEANLINESS]
Aloe pointed out the pathfinding code was wonky, this is the refactored version that also removes the `alien` var I added due to pathing jank.
> Refactors pathing and featherdoor access

- code/datums/abilities/flock/flockmind.dm
Response to @frawhst 's comment on assoc lists for stuctures
mildly cursed abuse of the fact that iterating over an assoc list gives you keys to reuse the tgui buttons list to also store the actual datum, but it's good and it works.
> assoc list gud

- _std/macros/flock.dm
- code/WorkInProgress/recycling/conveyor.dm
- code/datums/abilities/flock/flockmind.dm
- code/datums/flock/flock.dm
- code/mob/living/critter/ai/flock/flocktasks.dm
- code/mob/living/critter/flock/flockbit.dm
- code/mob/living/critter/flock/flockdrone.dm
- code/mob/living/intangible/flock/flockmind.dm
- code/mob/living/intangible/flock/flocktrace.dm
- code/modules/admin/player_options.dm
- code/modules/transport/pods/vehicle.dm
- code/obj/flock/cage.dm
- code/obj/flock/furniture.dm
- code/obj/flock/goods.dm
- code/obj/flock/structure/flock_structure_parent.dm
- code/obj/flock/structure/gnesisturret.dm
- code/obj/flock/structure/sentinel.dm
- code/obj/flock/trader.dm
- code/obj/item/device/radio.dm
- code/obj/item/organs/brain.dm
- code/obj/item/organs/heart.dm
- code/obj/machinery/computer/announcement.dm
- code/obj/machinery/door/feather.dm
- code/obj/machinery/launcherloader.dm
- code/obj/machinery/mass_driver.dm
- code/obj/stool.dm
- code/obj/window.dm
- code/procs/helpers.dm
- code/procs/mobprocs/chatprocs.dm
- code/turf/turf_flock.dm
[CLEANLINESS]
Yes this will conflict with literally everything.
Aloe wanted it
> Renames isflock to isflockmob

- code/datums/gamemodes/flock.dm
> Removed some unused procs in flock gamemode datum

- _std/macros/flock.dm
- code/datums/flock/flock.dm
- code/datums/flock/flockunlockable.dm
- code/modules/admin/admin_verbs.dm
- code/obj/flock/cage.dm
Makes achievements be defines, and alters a comment to better reflect updated code
> Azrun Code Review - Achievements

- code/mob/living/intangible/flock/flockmind.dm
> Ternaries bad, || good

- code/mob/living/critter/flockcritter_parent.dm
[CLEANLINESS]
Fixes the flockdrone repair action bar still paying repair cost if it somehow completes on a non-repairable type.
Azrun review
> Fixes a corner case that will probably never occur

- tgui/packages/tgui/interfaces/FlockPanel.js
Hopefully this is the correct incantation to ward off lawyers.
a l a n r e v i e w
> Added copyright message to flockpanel

- code/datums/flock/flock.dm
[CLEANLINESS]
Cursed over-atomization
a l a n r e v i e w
> Made a comment better

- code/obj/flock/cage.dm
- code/obj/flock/structure/collector.dm
- code/obj/flock/structure/gnesisturret.dm
Changes gnesis turret syringes to barbed, and slight buffs regen rate because oh my god was it slow
Removes old //TODO
Changes cage to use proper reagent init
> Aloe Review 2

- code/obj/machinery/mass_driver.dm
[CLEANLINESS]
isflockmob -> PROP_ATOM_FLOATING
a l a n r e v i e w
> Switches mass driver to use floating atom prop
