stonepillars/goon-flock

code/mob/living/critter/ai/flock/flockdrone.dm, code/mob/living/critter/ai/flock/flocktasks.dm
Tweaks the AI priorities, moving depositing mats on tealprints higher and building tiles lower.
Also, when building is selected, prioritises conversion of doors, walls, and lockers to increase access to new materials for harvesting.
Fixes #11
=> Slight tweaks to flockdrone AI to prioritise building material deposits and conversion of walls/doors/closets

code/datums/abilities/flockdrone.dm, code/datums/hud/flockdrone.dm, code/mob/living/critter/flock/flockdrone.dm, goonstation.dme
[QOL]
Fixes #31 and moves the drone eject button to the bottom left to match the AI shell eject button.
Knowing how many resources you have as a drone is good
=> Added a drone resource display and moved some HUD elements around to make room

code/datums/abilities/flock/flockmind.dm, code/datums/flock/flock.dm, code/datums/flock/flocktilegroup.dm, code/mob/living/critter/flock/flockdrone.dm, code/mob/living/critter/flockcritter_parent.dm, code/mob/living/intangible/flock/flockmind.dm, code/mob/living/intangible/flock/flocktrace.dm, code/mob/living/intangible/flockmob_parent.dm, code/obj/flock/structure/collector.dm, code/obj/flock/structure/egg.dm, code/obj/flock/structure/flock_structure_parent.dm, code/obj/flock/structure/rift.dm, code/obj/flock/structure/sentinel.dm, code/turf/turf_flock.dm
Establishes the base of the compute resource, adding a couple of utility functions and a UI element to the flockmind/flocktrace ability holder.
Also added the check that ensures flocktraces die when there is insufficient compute power.
Collectors also provisionally generate compute based on the number of tiles they were connected to. This should probably be changed, but makes a handy test case until we decide how it should change.
Sentinels now check to see if there is 20 available compute, and are active if this is the case. Previously this was a check on power.
Notably the code for tilegroups seems to have been exclusively used for determining power generation/consumption in a localised way. I've taken the power part out but left the tile grouping code in. Maybe we can use it for …
=> Flock Compute Base

code/datums/abilities/flock/flockmind.dm
This PR prevents creating tealprints on tiles that have something with density, excluding Flockdrones since they can move through fully constructed tealprint structures.
It also adds a different message for if there's a tealprint scheduled on a tile versus a finished tealprint structure when trying to schedule a tealprint.
It doesn't make sense that you can schedule a tealprint on a tile containing something with density.
=> Prevent creating tealprints on tiles that have something with density

code/datums/abilities/flock/flockmind.dm
This PR restricts placement of the initial Flockmind rift. The conditions that the initial blob nucleus placement has are used, along with solar panel and mining magnet areas to prevent rift spawned things from being flung out into space. There may be a few cases on maps where stuff could still be flung out into space, but this should help prevent most of it I think.
Flockmind rift placement isn't restricted right now.
Fixes #52.
=> Restrict Flockmind rift placement

code/datums/abilities/flock/flockmind.dm
[FEATURE][QOL]
This PR just allows you to undesignate enemies using the Designate Enemy ability.
It allows you to undesignate people you don't want enemies quicker.
Fixes #45.
=> Allow Designate Enemy ability to undesignate enemies

code/obj/machinery/computer/announcement.dm
[BUG]
Flock could previously make plain english announcements, now they can't. Also the announcement sound is replaced with a flock spooky.
Flocktraces are no longer able to announce "Relay is sus ඞ"
=> Makes flock using announcement computers come out garbled

code/mob/living/critter/flock/flockbit.dm, code/mob/living/critter/flock/flockdrone.dm, code/mob/living/intangible/flock/flockmind.dm, code/mob/living/intangible/flock/flocktrace.dm
[FEATURE][BUG]
This PR just updates name tags for all living Flock creatures.
They previously didn't have their name tags updated after their names were set. 
This will allow you to hold alt to view the names of Flocktraces, and the Flockmind's name. 
It also fixes Flockdrones and Flockbits having different alt-viewed names (weird glowy thing and floaty gewgaw) than their right-click names.
=> Update name tags for living Flock

code/datums/abilities/flock/flockmind.dm, code/datums/flock/flock.dm
[BUG]
This PR fixes not being able to priority designate space tiles as Flockmind.
Bug fix
=> Fix not being able to designate space tiles

code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR prevents you from attempting to deposit resources to a tealprint when controlling a Flockdrone and you have none.
Bug fix, fixes #14.
=> Fix depositing resources to a tealprint when you have none

code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR fixes a bug where when possessing a Flockdrone, it would show on the HUD your intent being help, when it was not.
Bug fix, fixes #16.
=> Fix Flockdrone possession showing wrong intent on HUD

code/mob/living/critter/flockcritter_parent.dm
[BUG]
This PR just fixes a bug where when cancelling converting a tile the overlay that gets applied is not removed right away.
Bug fix, fixes #66.
=> Fix cancelling Flockdrone tile conversion not removing overlay

code/datums/controllers/action_controls.dm, code/mob/living/critter.dm, code/mob/living/critter/ai/flock/flocktasks.dm
[QOL] [AI]
Fixes #46 by adding a reference on critter to the currently butchering mob.
3 flockdrones all standing around butchering the same corpse is inefficient
=> Fixed multiple flockdrones butchering the same corpse

code/datums/flock/flockprotection.dm, goonstation.dme
This PR adds a backend flock protection component. It's meant to be added to anything Flock owned, and it handles the cases of preventing Flockdrones from attacking the thing it's added to, as well as if attacking the thing is to be reported by a nearby Flockdrone or not.
This is a base component that will likely be modified later. It doesn't currently handle projectile attacks, and it doesn't handle distinguishing between stuff owned by different Flocks.
For having anything Flock owned have the properties of being immune to Flockdrone attacks and being reported to be attacked automatically by a Flockdrone, this would help make a single place where this sort of code can be modified.
=> Add Flock protection component

code/turf/turf_flock.dm
[BUG]
This PR just prevents Flock floor tiles from being burned.
Fixes a bug where burned Flock floor tiles would show up as a black square due to not having a burned icon.
Not sure if they should be burned or not, but this fixes this until an icon is made.
Prevents the burnt = 1 variable from being set, which could fix other possible bugs or mess with something else.
=> Prevent Flock floor tiles from being burned

code/turf/turf_flock.dm
[BUG]
This PR just fixes hitting Flock floor tiles not playing sound.
The line for sound that's supposed to play for when Flock floor tiles are on was commented out.
Bug fix.
Playing a sound for every Flock floor tile that is on causes a bit of sound spam, not sure how much of an issue it really is.
=> Fix Flock floor tile sounds not playing

code/modules/items/specials/ItemSpecials.dm
[BUG]
This PR fixes being able to fling Flock floor tiles with a crowbar.
It shouldn't be able to happen with Flock floor tiles needing to be damaged and removed manually with a crowbar.
=> Fix being able to fling Flock floor tiles

code/obj/flock/structure/relay.dm
[BUG]
Fixes #68
I'm not aware of any cases where the relay should render behind a map object.
Big spooky relay shouldn't be behind lightswitches
=> Flock relay now renders over everything

code/mob/living/critter/flockcritter_parent.dm
Fixes #104 
Note that the blood splatter decal is black because it has the same bug as haemochromatia in the upstream
=> changes flock critter blood to gnesis

code/mob/living/critter/ai/flock/flocktasks.dm
Card groups pop a context-menu when you use them, instead of being picked up. I added special handling that emulates the pick-up-deck action.
Some items are weird.
=> add special handling for card_groups

code/datums/abilities/flock/flockmind.dm, code/mob/living/intangible/flock/flockmind.dm, code/mob/transform_procs.dm
This PR brings the ghost Flocktrace offer up to date, making it TGUI, and allowing for declining all future Flocktrace offers.
The standardized way for getting candidates, dead_player_list(), is used.
Currently the Flockmind's death seems to still allow Flocktraces to spawn, not sure why. May just be the way I'm testing it.
It allows for a standardized way of getting candidates.
Declining future Flocktrace offers would be nice if you aren't interested. Fixes #8.
=> Bring ghost Flocktrace offer up to date with other offers

code/mob/living/intangible/flockmob_parent.dm
=> Fixed flockminds not being able to use certain hotkeys

code/obj/flock/cage.dm, code/obj/flock/furniture.dm
This PR just adds system integrity messages, showing the health %, for Flock closets, cages, and barricades.
It adds a bit more depth, and it would be nice to be able to see the health of these structures.
=> Add some more system integrity messages

code/obj/flock/cage.dm
[BUG]
This PR just fixes a bug with Flock cage health where it could have up to two times its starting value.
Bug fix. Don't think it would be good to have randomization for Flock cage health.
=> Fix cage health

code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR prevents creating barricades on tiles that have an object with density on them, excluding Flockdrones since they can move through barricades, and in-construction tealprints.
Bug fix.
=> Fix creating barricades on tiles they shouldn't be able to be made on

code/obj/flock/furniture.dm
[BUG]
This PR just adds some restrictions to the Flockcloset, such as preventing disassembly by wrench or welding holes in it with a welding tool.
Also fixes Flockdrones not being able to put items in Flockclosets.
Stuff such as disassembly by wrench shouldn't be allowed.
Bug fix.
=> Add Flockcloset attackby restrictions

code/mob/living/critter/flockcritter_parent.dm, code/turf/turf_flock.dm
[FEATURE]
This PR just changes how Flockwalls are deconstructed by Flockdrones. Instead of being turned into a gnesis girder with gnesis sheets over a gnesis floor tile, the wall will be replaced by a Flock floor tile, with no resources spawned (temporary).
Feels like it doesn't make sense with how it's currently done.
=> Change how Flockwalls are deconstructed

code/mob/living/critter/flock/flockdrone.dm
[FEATURE]
This PR allows the incapacitor Flockdrones have to point blank.
It also does some related minor cleanup regarding variables set for its limbs.
Point blanking is a feature of any gun.
Also prevents having your legs removed to be immune to Flockdrone attacks.
=> Allow Flockdrone incapacitor to point blank

code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR fixes a bug where blocking as a Flockdrone could trigger the anti-grapple system on yourself.
Bug fix.
=> Prevent blocking from shocking Flockdrones

code/mob/living/intangible/flock/flocktrace.dm
[BUG]
This PR fixes a bug where Flocktraces would die at 100 compute, and likely multiples of 100.
Also changes one of the Flocktrace death messages a little.
Bug fix.
=> Fix flocktraces dying at 100 compute

code/datums/abilities/flock/flockmind.dm, code/mob/living/intangible/flock/flockmind.dm
This PR just makes it so that the Flock Control Panel ability is added to your abilities after spawning your rift.
It also changes the name and description of the ability slightly.
It's not used before spawning the rift. Just minor cleanup.
=> Add flock control panel to abilities after rift spawn

code/mob/living/critter/flock/flockdrone.dm
Flockdrone projectiles can now hit targets that are lying down, and cause a small amount of burn damage also.
Flockdrones are useless if you're lying down. And being repeatedly stunned is frequently little more than annoying.
=> Flockdrone projectile buff

code/mob/living/critter/flockcritter_parent.dm
[BUG]
This PR fixes being able to heal Flockdrones with wires and welding tools.
It doesn't make sense for them to be healed using wires and welding tools.
=> Fix being able to heal Flockdrones with wires and welding tools

code/mob/living/critter/flock/flockdrone.dm
Flockdrone corpses no longer block movement or bullets. Also death of a drone ends all lifeprocesses because it ought to, and it was making things dense when they weren't supposed to be.
Fixes #132
=> Makes flockdrone density work properly

code/obj/flock/furniture.dm
[RUNTIME]
This PR fixes a runtime error that happens when closing a Flockcloset over another closet.
Runtime fix.
=> Fix Flockcloset runtime when closing over another closet

code/mob/living/critter/ai/flock/flocktasks.dm
[BUG]
Fixes #141
So it turns out that if you set `can_attack` to true on a ranged critter limb, they will only ever try to melee attack unless you explicitly force them to ranged attack, leading to drones just sitting several tiles away trying to grab their target.
Drones being able to attack is good
=> Fixes AI drones not being able to attack

code/turf/turf_flock.dm
[FEATURE]
This PR just makes it so that broken Flockwalls don't reflect energy projectiles.
Adds another feature to broken Flockwalls besides preventing Flockwalls from floorrunning.
Think it would make a bit more sense too in that a Flockwall riddled with cracks wouldn't reflect an energy projectile very well.
=> Disallow broken walls from reflecting energy projectiles

code/obj/stool.dm
This PR just makes it so that Flockdrones and Flockbits can't be buckled.
Flockdrones and Flockbits if buckled just stay buckled right now. Handling buckling requires touching AI code, posing a bit of a hassle, and besides the gimmick of buckling, there isn't really anything desired in being able to buckle one.
=> Prevent buckling of Flockdrones and Flockbits

code/obj/flock/structure/flock_structure_parent.dm
This PR just makes some minor adjustments/improvements for Flock structure attacks.
Some lines for effects were moved to before taking damage, so that any reporting of attacks and other similarly timed effects happen before the Flock structure is destroyed.
Some sound lines were moved to after the structure is destroyed, so that when destroying a Flock structure only one sound is played.
Attack particles for attacking by hand and with an object were added too.
Adjustments/improvements for proper ordering of effects.
Attack particles would be nice for hit feedback.
=> Make minor Flock structure attack adjustments/improvements

code/mob/living/critter/flock/flockdrone.dm
[FEATURE]
This PR makes it so that anyone who throws an object at a Flockdrone, that hits the Flockdrone, is marked as an enemy.
Currently, hitting a Flockdrone with a thrown object does damage to it, but you aren't marked as an enemy.
=> Mark people who throw objects at Flockdrones as enemies

code/modules/transport/pods/vehicle.dm
[BUG]
This PR prevents Flockdrones from entering vehicles.
They shouldn't be able to given the number of Flockdrones you could have and what a Flockdrone could do if able to pilot a vehicle in respect to their intended functions.
Fixes #137.
=> Prevent Flockdrones from entering vehicles

code/obj/machinery/door/feather.dm
[BUG]
This PR fixes a bug where you could set signals for Flockdoors with a multitool.
Bug fix.
=> Prevent setting signals for Flockdoors with multitools

code/mob/living/critter/flockcritter_parent.dm
This PR just gives Flockdrones and Flockbits radiation immunity.
They can't receive toxin damage, it doesn't seem right when a health analyzer shows a Flockdrone or Flockbit having radiation poisoning.
=> Give Flockdrones and Flockbits radiation immunity

code/datums/abilities/flock/flockmind.dm
[BUG]
This PR fixes a bug where you could diffract a dead drone.
Additional minor cleanup in the ability cast.
Bug fix.
=> Prevent diffracting dead drones

code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR just ends floorrunning when ejecting from a flockdrone.
Fixes some issues/bugs that could arise if ejecting when floorrunning.
=> End floorrunning when ejecting from a drone

code/mob/living/intangible/flock/flockmind.dm, code/obj/flock/structure/egg.dm, code/obj/flock/structure/rift.dm
[BUG]
This PR changes the Flockmind death condition to check for drones and certain structures rather than compute.
Fixes a bug where the Flockmind would still be alive even if all drones were dead.
Also, it structures the Flockmind death check in a way that removes the need for the Flock rift and eggs to have compute and allows future added objects or flock structures to be checked in the death check.
Bug fix (If the Flockmind loses all its drones but still has sources of compute, it cannot do anything.).
Don't think it makes sense for rift and eggs to provide compute.
=> Change Flockmind death condition

code/datums/abilities/flock/flockmind.dm, code/mob/living/critter/flock/flockdrone.dm, code/mob/living/critter/flockcritter_parent.dm
[BUG]
This PR fixes being able to heal dead Flockdrones with the Concentrated Repair Burst ability, Flockdrones being able to heal dead Flockdrones, healing Flockdrones as a Flockdrone making them call out that they have been damaged, and healing Flockdrones as a Flockdrone causing them to wait forever.
Bug fixes.
=> Fix some Flockdrone healing bugs

code/mob/living/critter/ai.dm
This just makes it so that interrupt immediately starts the next task instead of waiting for the next AI tick cycle. 
Makes flockdrones react significantly faster in combat (and when manually ordered by #181), allowing a decent number of them an actual chance at caging someone trying to punch them.
I'm scared that there's a reason that it didn't already work like this, but I can't see one for now.
=> Adds a tick() call to interrupt

code/datums/abilities/flock/flockmind.dm, code/mob/living/intangible/flock/flockmind.dm
[QOL]
Fixes #168
Partitioning shouldn't give flockminds a 30 second APM break
=> Fixes flockmind being unable to act while partitioning

code/datums/abilities/flock/flockmind.dm, code/datums/flock/flock.dm, code/datums/flock/flockunlockable.dm, code/mob/living/critter/ai/flock/flockdrone.dm, code/mob/living/critter/ai/flock/flocktasks.dm, code/mob/living/critter/flock/flockdrone.dm, code/mob/living/critter/flockcritter_parent.dm, code/mob/living/intangible/flock/flockmind.dm, code/obj/flock/structure/flock_structure_ghost.dm, code/obj/flock/structure/flock_structure_parent.dm
Adds bounds checking to the placement of flock structures with highlighting of the offending blockers
Adds a new ability: "Mark for Deconstruct" which sets existing flock structures (including walls/furniture/doors) to be targeted for deconstruction by nearby drones, refunding some resources where appropriate. Because good luck placing a 5x5 structure on basically any map.
Could use a little polish, namely: 
- Icon for marked as deconstruct should be different to the enemy one
- need an icon for the abilityHolder -currently reusing ping
Fixes #162
=> Adds bounds checking to large flock structures, plus ability to deconstruct flock stuff to clear space

code/mob/living/critter/flock/flockdrone.dm, code/turf/turf_flock.dm
[FEATURE]
This PR just adds a resource cost to floorrunning, with placeholder numbers used. When floorrunning, it costs resources per life tick, and when entering a Flocktile.
As implemented, it should be relatively straightforward to change this cost to something else, such as taking energy from an energy bar, if wanted in the future, and modify how often you lose resources, at least for when floorrunning to a new tile.
Floorrunning is powerful and needs something to prevent floorrunning indefinitely.
=> Add cost to floorrunning

code/datums/abilities/flock/flockmind.dm, code/datums/flock/flock.dm, code/mob/living/critter/ai/flock/flocktasks.dm
Clicking a thing marked for deconstruction will now stop it being deconstructed and interrupt drones who are on their way to do that.
=> Add toggleable deconstruction

code/mob/living/critter/ai.dm, code/mob/living/critter/ai/shared.dm
[BUG]
Moves the `holder.target = null` so it applies to all aiTasks by default
Fixes flockdrones trying to deconstruct walls with incapacitors and is probably just a good idea in general
=> Moves the target reset from sequence to aiTask

code/obj/flock/structure/flock_structure_ghost.dm
This PR just makes it so that ghost structures when destroyed drop their resources in a cube rather than scrap.
It fixes a possible farming issue if a ghost structure is destroyed with zero or few resources deposited. Simpler to work with resource cubes rather than possibly varying resources, in the future, from scrap.
=> Make ghost structures drop a resource cube on destruction instead of scrap

code/obj/machinery/door/feather.dm
[BUG]
This PR fixes a bug where Flockwalls wouldn't be connected to created Flockdoors, and it fixes a bug where Flockwalls wouldn't be disconnected from destroyed Flockdoors.
Bug fixes, fixes #103.
=> Fix walls by created and destroyed Flockdoors not updating properly

code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR fixes a bug where Flockdrones could report the dormant message for going out of range if sent to nullspace (I think, didn't test).
Bug fix.
=> Prevent drones from reporting dormancy on deletion

code/mob/living/critter/flockcritter_parent.dm, code/obj/flock/furniture.dm, code/obj/flock/structure/flock_structure_parent.dm, code/obj/machinery/door/feather.dm, code/obj/window.dm, code/turf/turf_flock.dm
[FEATURE][BUG]
This PR standardizes how material properties are set across all Flock stuff. It gives Flock stuff that didn't have the gnesis material the gnesis material, prevents some Flock stuff that had the gnesis material from showing that in its name and description, and fixes chairs and alcoves giving steel sheets when deconstructed.
Only thing I noticed was that Flock windows are now opaque. Wasn't sure if opacity should be set manually or the material itself changed.
Consistency and bug fixes.
=> Standardize material across Flock stuff

_std/defines/roles.dm, code/mob/living/intangible/flock/flocktrace.dm, code/mob/transform_procs.dm
Anyone who gets flocktrace'd will now be added to the antag list and recieve the little V symbol for admins
Fixes #235
=> Make flocktraces be antags

code/mob/living/critter/flock/flockdrone.dm, code/mob/living/intangible/flock/flockmind.dm, code/mob/living/intangible/flock/flocktrace.dm
[FEATURE]
This PR adds procs in that may be used elsewhere for allowing the Flockmind to promote Flocktraces to Flockmind.
It would be nice for the Flockmind to be able to give another entity control of the flock if they need to leave or go afk.
=> Add Flockmind promotion framework

_std/macros/vehicles.dm, code/datums/abilities/flock/flockmind.dm, code/datums/flock/flock.dm, code/mob/living/critter/ai/flock/flocktasks.dm, code/mob/living/critter/flock/flockdrone.dm
[BUG]
Hitting a drone with a pod laser now marks all occupants and the pod itself as enemies, drones will shoot at any pod that contains an enemy and if a drone sees you in an enemy pod you will be marked as an enemy.
Fixes #233
Also adds `isvehicle` because for some reason that didn't exist (probably missing a few types as well)
Pods are already a decent counter to flock, letting drones slowly mob them to death is important
=> Allow drones to attack pods

code/obj/flock/structure/relay.dm
[BALANCE]
Relay charge time from 600 -> 360 seconds.
"Overwhelming anomalous power signatures detected on station. This is an existential threat to the station. All personnel must contain this event."
10 minutes seemed like a very long time during playtesting, and right now there's no real indicator that the crew are supposed to immediately drop everything and destroy the relay so I've added a vague and slightly garbled announcement.
=> Cuts relay charge time to 6 minutes and adds a crew announcement for it

code/mob/living/critter/flock/flockdrone.dm
Fixes #238
it's normal for flockdrones to be attacked right after spawning.
=> Prevent flockdrones from admin messaging on attack after spawning

code/mob/living/critter/flockcritter_parent.dm
[BUG]
This PR just makes the Flockdrone abilities unresumable, based on what Pali suggested in the linked issue.
I guess this now makes some sound spam possible, which could be accounted for with cooldowns, but not sure if that was the best solution considering the sound isn't much of a problem for when you aren't intentionally doing that.
Bug fix, fixes #247.
Also fixes some related ability exploits possible by starting one of these abilities on a tile and ending it while on another tile and spam clicking over the distance, allowing you to do stuff such as converting a tile to flock from several tiles away.
=> Make Flockdrone abilities unresumable

code/mob/living/critter/flock/flockbit.dm, code/mob/living/critter/flock/flockdrone.dm, code/mob/living/critter/flockcritter_parent.dm
This PR just moves some stuff shared between Flockdrones and Flockcritters to parent procs.
Cleanliness.
=> Move shared Flock critter stuff to parent procs

_std/pathfinding.dm, code/obj/machinery/door/door_parent.dm, code/obj/machinery/door/feather.dm
[BUG]
Fixes #87, also modifies the pathfinding code slightly to account for doors with no access requirements that have `allowed` checks so beepsky doesn't bang his head.
While beepsky *is* the law, flock probably shouldn't respect the law.
=> Prevents beepsky from opening featherdoors

code/datums/flock/flock.dm
[runtime]
Fixes `null.disposed` runtimes by switching to `QDELETED`
Runtimes bad
=> Fix runtimes while checking for disposed busy stuff

_std/macros/flock.dm, code/datums/abilities/flock/flockmind.dm, code/mob/living/critter/flock/flockdrone.dm
[BUG]
This PR fixes being able to mark some Flock stuff for deconstruction and deconstruct some stuff that shouldn't be able to be marked or deconstructed.
Bug fix.
=> Restrict some Flock stuff from being marked for deconstruction or deconstructed

code/mob/living/critter/ai/flock/flockdrone.dm, code/mob/living/critter/ai/flock/flocktasks.dm, code/mob/living/critter/ai/shared.dm
Makes wandering smarter for flockdrones. They now avoid space tiles, actively path away from where they started wandering, and use smarter pathing. They also head back towards the station if they somehow end up in space.
Previous behaviour sucked.
=> Better wandering

code/WorkInProgress/recycling/conveyor.dm, code/obj/machinery/launcherloader.dm, code/obj/machinery/mass_driver.dm
[FEATURE]
This PR just makes it so that Flockdrones and Flockbits can't be moved by conveyor belts and mass driver type pushers.
It doesn't make sense considering Flockdrones and Flockbits are floating. 
It also wouldn't be good to lose them if they move onto these objects considering how valuable they can be.
=> Prevent Flockdrones and Flockbits from being moved by conveyors and drivers

code/datums/flock/flock.dm
[two line PR]
Makes pinging a turf apply an alpha mask to the ping overlay so it doesn't obscure the atoms on the turf. It's limited to turfs because it looks very weird on other things.
Pinging the turf vs pinging a thing on the turf.
Looks better
=> Makes pinging turfs a little less weird

code/mob/living/critter/flock/flockdrone.dm, code/obj/item.dm
This PR reworks and improves item absorption.
Makes variable names more intuitive.
Resources gained per item health absorbed are reduced.
Item eating is now serial based.
Items are stopped from burning on equip.
Rounding is done for absorbed resources.
Resources are no longer given from absorption completion.
Messages for absorbing items are modified to reduce chat spam.
Alternative pr to #208.
Fixes #80.
More clear variable names are nice.
Resources gained reduced based on playtesting.
Item stacks shouldn't be dissolved like a single item.
Wouldn't want an item being burned at the same time as being reclaimed.
Rounding checks prevent fractional resources.
Doesn't make sense to have resources given on item absorption, given that the item is supposed to be absorbed already.
Chat spam …
=> Rework and improve item absorption

code/datums/flock/flock.dm, code/obj/flock/structure/relay.dm
[BUG]
This PR just adds a flock parameter to Flock mass conversion procs, also making the relay use it.
Fixes a bug where stuff converted to Flock by the relay wasn't registering its Flock.
Would be nice to have for the other proc if wanted to be used.
=> Add flock parameter to Flock mass conversion procs

code/datums/flock/flockprotection.dm, code/mob/living/critter/flock/flockdrone.dm, code/mob/living/critter/flockcritter_parent.dm
[BUG]
Fixes #295 and several adjacent bugs in flockdrone harm reporting code, including a condition which checked a proc which always returned false and the protection component mixing up thrown and projectile flags.
Walls are now far less threatening.
=> Fixes very threatening walls

code/mob/living/critter/ai/flock/flocktasks.dm, code/mob/living/critter/flock/flockdrone.dm
Prevents building (converting walls/floors) before 10 drones
Slightly higher absorbtion rate, still lower than original.
Drones weren't reproducing and until all the walls around them were converted, and it was really slowing down the earlygame.
=> Minor balance change

code/mob/living/critter/flock/flockdrone.dm, code/obj/item/paper.dm
[BUG]
Fixes the flockdrone absorber not clearing its item reference on qdel, leading to it holding a qdeled item and causing jank. Since this was originally a paper bin bug I also stopped paper bins having 100 health because that seems a lot and I haven't learned my lesson about atomization.
infinitely absorbing paper bins getting stuck in drones is bad
=> Fixed some flockdrone absorber jank and nerfed paperbin health

code/datums/flock/flock.dm
structures explode into gnesis juice and glass when the flock dies. 
no runtimes, also gives a clear indicator that winning has happened.
fixes #306
=> gib structures on suicide

code/datums/abilities/flock/flockmind.dm
[BUG]
Moves the space/solars/mining magnet check inside a `!isadmin` block so admins can spawn the rift wherever.
=> Lets admins spawn flock rift in space

code/atom.dm, code/mob/living/critter/flock/flockdrone.dm
[BUG]
Removes the cursed pull check in `atom.dm` and replaces it with defining drones as restrained while floorrunning.
This will prevent right click pulling too, if https://github.com/goonstation/goonstation/pull/8726 gets merged.
=> Defines flockdrones as restrained while floorrunning

code/mob/living/critter/flock/flockdrone.dm, code/turf/turf_flock.dm
[BUG]
The flockdrone antigrab system wasn't actually working if the drone was AI controlled, since it was in client called movement code. I've moved it into the life loop, so now it just activates after a certain number of life loop calls.
Also fixed pins not working on flock tiles because it's related shut up.
no grabbing drones >:(
=> Fixes some grab jank

code/mob/living/critter/flock/flockdrone.dm, code/obj/flock/structure/egg.dm, code/obj/flock/structure/rift.dm
[BALANCE]
Partially reverts the nerfs to flockdrone resource absorption from #270.
Flockdrones now gain 4 resources per health absorbed.
The flock rift now comes with an extra egg containing 3 flockbits.
Flockdrones were replicating at an extremely slow rate, meaning they were basically unable to sustain any real losses incurred. 
The nerf cut the rate at which flock could gain resources by around 4 times, this caused flock to not really work anymore.
=> Revert nerfs to flockdrone absorption

code/obj/flock/cage.dm, code/obj/flock/structure/gnesisturret.dm, code/obj/flock/structure/sentinel.dm, code/obj/machinery/door/feather.dm
Doors now have 200 health (up from 80) - ~30ish toolbox hits
Turrets cost 150 each
Cages inject their occupant with gnesis when they get down to ripping out flesh parts
Cages are harder to break out of now - you will definitely lose a sizeable portion of items if you get caged
Balance
=> Cage + Turret Cost Balance
